WhiteLagoon.Web/Models/ErrorViewModel.cs
namespace WhiteLagoon.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WhiteLagoon.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WhiteLagoon.Web.Models;

namespace WhiteLagoon.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        
        public IActionResult Error()
        {
            return View();
        }
    }
}

WhiteLagoon.Web/Controllers/VillaController.cs
using Microsoft.AspNetCore.Mvc;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Infrastructure.Data;

namespace WhiteLagoon.Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly ApplicationDbContext applicationDbContext;

        public VillaController(ApplicationDbContext applicationDbContext)
        {
            this.applicationDbContext = applicationDbContext;
        }
        public IActionResult Index()
        {
            var villas = applicationDbContext.Villas.ToList();
            return View(villas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Villa villa)
        {
            //if(villa.Name == villa.Description)
            //{
            //    ModelState.AddModelError("", "Name and Description cannot be the same");
            //}

            if (ModelState.IsValid)
            {
                applicationDbContext.Add(villa);
                applicationDbContext.SaveChanges();
                TempData["success"] = "The Villa has been created successfully.";
                return RedirectToAction("Index");
            }
            TempData["error"] = "The Villa could not be created.";
            return View(villa);
            
        }

        public IActionResult Update(int villaId)
        {
            Villa? obj = applicationDbContext.Villas.FirstOrDefault(u => u.Id == villaId);

            //Other ways to get data from DB
            //var villaDetails =  applicationDbContext.Villas.Where(u => u.Price > 250 && u.Occupancy > 0).FirstOrDefault();
            //var villaDetails2 = applicationDbContext.Villas.Find(villaId);

            if (obj == null)
            {
                //return NotFound();
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Update(Villa villa)
        {
            if (ModelState.IsValid)
            {
                applicationDbContext.Update(villa);
                applicationDbContext.SaveChanges();
                TempData["success"] = "The Villa has been updated successfully.";
                return RedirectToAction("Index");
            }
            TempData["success"] = "The Villa could not be updated.";
            return View(villa);
        }

        public IActionResult Delete(int villaId)
        {
            Villa? obj = applicationDbContext.Villas.FirstOrDefault(u => u.Id == villaId);

            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Delete(Villa villa)
        {
            Villa? objFromDb = applicationDbContext.Villas.FirstOrDefault(u => u.Id == villa.Id);

            if (objFromDb is not null)
            {
                applicationDbContext.Remove(objFromDb);
                applicationDbContext.SaveChanges();
                TempData["success"] = "The Villa has been deleted successfully.";
                return RedirectToAction("Index");
            }
            TempData["error"] = "The Villa could not be deleted.";
            return View(villa);
        }
    }
}

WhiteLagoon.Web/Controllers/VillaNumberController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Infrastructure.Data;

namespace WhiteLagoon.Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly ApplicationDbContext applicationDbContext;

        public VillaNumberController(ApplicationDbContext applicationDbContext)
        {
            this.applicationDbContext = applicationDbContext;
        }
        public IActionResult Index()
        {
            var villaNumbers = applicationDbContext.VillaNumbers.ToList();
            return View(villaNumbers);
        }

        public IActionResult Create()
        {
            IEnumerable<SelectListItem> list = applicationDbContext.Villas.ToList().Select(v => new SelectListItem
            {
                Text = v.Name,
                Value = v.Id.ToString()
            }); 

            ViewData["VillaList"] = list;
            return View();
        }

        [HttpPost]
        public IActionResult Create(VillaNumber villaNumber)
        {
            //ModelState.Remove("Villa");  //One way to remove the validation of property 
            if (ModelState.IsValid)
            {
                applicationDbContext.Add(villaNumber);
                applicationDbContext.SaveChanges();
                TempData["success"] = "The Villa Number has been created successfully.";
                return RedirectToAction("Index");
            }
            TempData["error"] = "The Villa Number could not be created.";
            return View(villaNumber);
            
        }
        /*
        public IActionResult Update(int villaId)
        {
            Villa? obj = applicationDbContext.Villas.FirstOrDefault(u => u.Id == villaId);

            //Other ways to get data from DB
            //var villaDetails =  applicationDbContext.Villas.Where(u => u.Price > 250 && u.Occupancy > 0).FirstOrDefault();
            //var villaDetails2 = applicationDbContext.Villas.Find(villaId);

            if (obj == null)
            {
                //return NotFound();
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Update(Villa villa)
        {
            if (ModelState.IsValid)
            {
                applicationDbContext.Update(villa);
                applicationDbContext.SaveChanges();
                TempData["success"] = "The Villa has been updated successfully.";
                return RedirectToAction("Index");
            }
            TempData["success"] = "The Villa could not be updated.";
            return View(villa);
        }

        public IActionResult Delete(int villaId)
        {
            Villa? obj = applicationDbContext.Villas.FirstOrDefault(u => u.Id == villaId);

            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Delete(Villa villa)
        {
            Villa? objFromDb = applicationDbContext.Villas.FirstOrDefault(u => u.Id == villa.Id);

            if (objFromDb is not null)
            {
                applicationDbContext.Remove(objFromDb);
                applicationDbContext.SaveChanges();
                TempData["success"] = "The Villa has been deleted successfully.";
                return RedirectToAction("Index");
            }
            TempData["error"] = "The Villa could not be deleted.";
            return View(villa);
        }
        */
    }
}

WhiteLagoon.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WhiteLagoon.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@* <html lang="en" data-bs-theme="dark"> *@
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WhiteLagoon.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet"  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="~/WhiteLagoon.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width:35px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Villa" asp-action="Index">Villa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="VillaNumber" asp-action="Index">Villa Number</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2025 - WhiteLagoon
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WhiteLagoon.Web/Views/Shared/_Notification.cshtml
@if(TempData["error"]!=null)
    {
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script type="text/javascript">
                toastr.success('@TempData["error"]');
        </script>
    }
@if (TempData["success"] != null)
    {
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script type="text/javascript">
            toastr.success('@TempData["success"]');
        </script>
    }

WhiteLagoon.Web/Views/Villa/Create.cshtml
@* @model WhiteLagoon.Domain.Entities.Villa *@
@* above one has been defined in '_ViewImport.cshtml' *@

@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row"> 
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Villa</h2>
            </div>
        </div>
    </div>
</div>

<div class="card-body border p-4">  
    <form method="post" class="row">
        <div class="p-3">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Name" class="form-control border shadow" placeholder="Name" />
                <label asp-for="Name" class="ms-1">Name</label>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Description" class="form-control border shadow" placeholder="Description" />
                <label asp-for="Description" class="ms-1">Description</label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Price" class="form-control border shadow" placeholder="Price" />
                <label asp-for="Price" class="ms-1">Price</label>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Sqft" class="form-control border shadow" placeholder="Sqft" />
                <label asp-for="Sqft" class="ms-1">Sqft</label>
                <span asp-validation-for="Sqft" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Occupancy" class="form-control border shadow" placeholder="Occupancy" />
                <label asp-for="Occupancy" class="ms-1">Occupancy</label>
                <span asp-validation-for="Occupancy" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.ImageUrl" class="form-control border shadow" placeholder="ImageUrl" />
                <label asp-for="ImageUrl" class="ms-1">ImageUrl</label>
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
           
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"></i> Create
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i> Cancel
                    </a>
                </div>
            </div>
            
        </div>
    </form>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLagoon.Web/Views/Villa/Delete.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Villa</h2>
            </div>
        </div>
    </div>
</div>

<div class="card-body border p-4">
    <form method="post" class="row">
        <input asp-for="@Model.Id" hidden />
        <div class="p-3">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Name" disabled class="form-control border shadow" placeholder="Name" />
                <label asp-for="Name" class="ms-1">Name</label>
               
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Description" disabled class="form-control border shadow" placeholder="Description" />
                <label asp-for="Description" class="ms-1">Description</label>
               
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Price" disabled class="form-control border shadow" placeholder="Price" />
                <label asp-for="Price" class="ms-1">Price</label>
   
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Sqft" disabled class="form-control border shadow" placeholder="Sqft" />
                <label asp-for="Sqft" class="ms-1">Sqft</label>
               
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Occupancy" disabled class="form-control border shadow" placeholder="Occupancy" />
                <label asp-for="Occupancy" class="ms-1">Occupancy</label>
                
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.ImageUrl" disabled class="form-control border shadow" placeholder="ImageUrl" />
                <label asp-for="ImageUrl" class="ms-1">ImageUrl</label>
                
            </div>

            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-danger w-100">
                        <i class="bi bi-trash-fill"></i> Delete
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i> Cancel
                    </a>
                </div>
            </div>

        </div>
    </form>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLagoon.Web/Views/Villa/Index.cshtml
@model IEnumerable<WhiteLagoon.Domain.Entities.Villa>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Villa List</h2>
            </div>
        </div>
    </div>
</div>

<div class="card-body border p-4">
    <div class="row pb-3">
        <div class="col-6 offset-6 text-end">
            <a asp-controller="Villa" asp-action="Create" class="btn btn-secondary">
                <i class="bi bi-plus-circle"></i> Create New Villa
            </a>
        </div>
    </div>
</div>

<div class="table table-bordered p-4">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Sqft</th>
                <th>Occupancy</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Price</td>
                    <td>@item.Sqft</td>
                    <td>@item.Occupancy</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Villa" asp-action="Update" asp-route-villaId="@item.Id" class="btn btn-success mx-2">
                                <i class="bi bi-pencil-square"></i>
                                Edit
                            </a>
                            <a asp-controller="Villa" asp-action="Delete" asp-route-villaId="@item.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-trash-fill"></i>
                                Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

WhiteLagoon.Web/Views/Villa/Update.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Villa</h2>
            </div>
        </div>
    </div>
</div>

<div class="card-body border p-4">
    <form method="post" class="row">
        <input asp-for="@Model.Id" hidden />
        <div class="p-3">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Name" class="form-control border shadow" placeholder="Name" />
                <label asp-for="Name" class="ms-1">Name</label>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Description" class="form-control border shadow" placeholder="Description" />
                <label asp-for="Description" class="ms-1">Description</label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Price" class="form-control border shadow" placeholder="Price" />
                <label asp-for="Price" class="ms-1">Price</label>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Sqft" class="form-control border shadow" placeholder="Sqft" />
                <label asp-for="Sqft" class="ms-1">Sqft</label>
                <span asp-validation-for="Sqft" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Occupancy" class="form-control border shadow" placeholder="Occupancy" />
                <label asp-for="Occupancy" class="ms-1">Occupancy</label>
                <span asp-validation-for="Occupancy" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.ImageUrl" class="form-control border shadow" placeholder="ImageUrl" />
                <label asp-for="ImageUrl" class="ms-1">ImageUrl</label>
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"></i> Update
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i> Cancel
                    </a>
                </div>
            </div>

        </div>
    </form>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLagoon.Web/Views/VillaNumber/Create.cshtml
@* @model WhiteLagoon.Domain.Entities.Villa *@
@* above one has been defined in '_ViewImport.cshtml' *@

@model VillaNumber

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Villa Number</h2>
            </div>
        </div>
    </div>
</div>

<div class="card-body border p-4">
    <form method="post" class="row">
        <div class="p-3">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-floating py-2 col-12">
                @* <input asp-for="@Model.Id" class="form-control border shadow" placeholder="Name" /> *@
                <select asp-for="@Model.Id" asp-items="@ViewData["VillaList"] as IEnumerable<SelectListItem>"
                    class="form-select border shadow">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <label asp-for="Id" class="ms-1">Villa Id</label>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Villa_Number" class="form-control border shadow" placeholder="Description" />
                <label asp-for="Villa_Number" class="ms-1">Villa Number</label>
                <span asp-validation-for="Villa_Number" class="text-danger"></span>
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.SpecialDetails" class="form-control border shadow" placeholder="Price" />
                <label asp-for="SpecialDetails" class="ms-1">SpecialDetails</label>
                <span asp-validation-for="SpecialDetails" class="text-danger"></span>
            </div>
            
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"></i> Create
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i> Cancel
                    </a>
                </div>
            </div>

        </div>
    </form>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLagoon.Web/Views/VillaNumber/Index.cshtml
@model IEnumerable<VillaNumber>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Villa Number List</h2>
            </div>
        </div>
    </div>
</div>

<div class="card-body border p-4">
    <div class="row pb-3">
        <div class="col-6 offset-6 text-end">
            <a asp-controller="VillaNumber" asp-action="Create" class="btn btn-secondary">
                <i class="bi bi-plus-circle"></i> Create New Villa Number
            </a>
        </div>
    </div>
</div>

<div class="table table-bordered p-4">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Villa Name</th>
                <th>Villa Number</th>
                <th>Special Details</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Villa_Number</td>
                    <td>@item.SpecialDetails</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Villa" asp-action="Update" asp-route-villaNumberId="@item.Villa_Number" class="btn btn-success mx-2">
                                <i class="bi bi-pencil-square"></i>
                                Edit
                            </a>
                            <a asp-controller="Villa" asp-action="Delete" asp-route-villaNumberId="@item.Villa_Number" class="btn btn-danger mx-2">
                                <i class="bi bi-trash-fill"></i>
                                Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>